# Generated by Django 4.2.3 on 2023-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='active',
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.BooleanField(default=True, verbose_name='Released'),
        ),
    ]
