# Generated by Django 4.2.3 on 2023-08-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_remove_movie_active_movie_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('released', models.BooleanField(default=True, verbose_name='Released')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ManyToManyField(to='watchlist.country')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.media')),
            ],
        ),
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('website', models.URLField(max_length=100)),
                ('countries', models.ManyToManyField(to='watchlist.country')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='movieplatform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.streamplatform'),
        ),
        migrations.AddField(
            model_name='media',
            name='platforms',
            field=models.ManyToManyField(related_name='media', to='watchlist.streamplatform'),
        ),
    ]
