# Generated by Django 4.2.3 on 2023-08-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_country_media_movieplatform_streamplatform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviePlatform',
            new_name='MediaPlatform',
        ),
    ]
