# Generated by Django 4.2.3 on 2023-08-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0012_alter_media_language'),
    ]

    operations = [
        
    ]
