# Generated by Django 4.2.3 on 2023-08-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0013_alter_media_language'),
    ]

    operations = [
       
    ]
