# Generated by Django 4.2.3 on 2023-08-14 12:12

from django.db import migrations, models
import django.db.models.deletion
import watchlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0017_media_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[watchlist.models.rating_range_assertion])),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.media')),
            ],
        ),
    ]
