# Generated by Django 4.2.3 on 2023-08-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0020_review_avg_rating_review_no_of_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='no_of_ratings',
        ),
        migrations.AddField(
            model_name='media',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='no_of_ratings',
            field=models.FloatField(default=0),
        ),
    ]
